### PR TITLE
Fix asciidoctor-epub3 issues + bump to 2.0.6

### PR DESCRIPTION
**Pull request by dduportal**
This PR introduces the following changes:

- Gem `asciidoctor` bumped to 2.0.6
- Gem `asciidoctor-epub3` bumped to 1.5.0.alpha**9**

Why this PR comes from?

- https://github.com/asciidoctor/docker-asciidoctor/pull/89#issuecomment-478726163
- https://github.com/asciidoctor/docker-asciidoctor/pull/89#issuecomment-480082233

### CODE REVIEW

**Comment by dduportal** [comment]
Hello @mojavelinux @cexbrayat @hakandilek @marcelhuberfoo ,

Here is the latest bump trying to fix epub3. There is a commented test added to verify it's working. However, I have the same error on both combination: (asciidoctor 2.0.0 + asciidoctor-epub3 1.5.0.alpha8) and (asciidoctor 2.0.0 + asciidoctor-epub3 1.5.0.alpha9).

The error is the following:

```shell
undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x0000560f1177b188>
     Use --trace for backtrace
```

I need help on this one :)

**Comment by mojavelinux** [comment]
@dduportal That's an indication the input is malformed. It's not following the structure required by Asciidoctor EPUB3. It's best to use draw from this sample: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/data/samples/sample-book.adoc (you only need the sample-content.adoc chapter).

**Comment by mojavelinux** [comment]
(In other words, you can't just point Asciidoctor EPUB3 at any document. It has to adhere to a particular structure because it gets chopped up differently than with other output formats).

**Comment by dduportal** [comment]
Thanks @mojavelinux , I have learned a new cool stuff today, based on your feedback 👍 

PR updated with a test case for epub. WDYT @cexbrayat ?

**Comment by cexbrayat** [comment]
@dduportal PR looks good, thanks Damien :+1:. I gave it a try locally, and I no longer run into the error we had. I have regressions though but I'll open issues into `asciidoctor-epub` or `asciidoctor`.

**Comment by cexbrayat** [comment]
I filed an issue https://github.com/asciidoctor/asciidoctor-epub3/issues/188 
It looks unrelated to asciidoctor v2, because I reproduce with the latest master and just àsciidoctor-epub3@1.5.0-alpha.9`

**Comment by dduportal** [comment]
Thanks for the fast feedback @cexbrayat !

I'm taking on myself to merge this now to make the master (more) stable.

**Pull request merged**
