### PR TITLE
Update asciidoctor-pdf to 1.5.0.beta.7

### PR DESCRIPTION
**Pull request by juracy**

### CODE REVIEW

**Comment by juracy** [comment]
@dduportal Docker hub is still with an older version of docker-asciidoctor, with asciidoctor-pdf 1.5.0.beta.5!

**Comment by dduportal** [comment]
@juracy that's right. Currently checking this. Travis build is OK, but nit Docker's hub.

**Comment by dduportal** [comment]
@juracy thanks a lot. I've opened an issue as I can't fix this: https://github.com/asciidoctor/docker-asciidoctor/issues/115

**Comment by mojavelinux** [comment]
I'm on it.

**Comment by dduportal** [comment]
Fixed, thanks all!

https://github.com/asciidoctor/docker-asciidoctor/issues/115#issuecomment-557003234

**Pull request merged**
