### PR TITLE
chore(README for DockerHub): bump Pandoc to `3.1.12.1` and track its version with `updatecli`

### PR DESCRIPTION
**Pull request by gounthar**
I tested locally, and the recent versions of `pandoc` work with this `Makefile`.

Therefore, I suggest using a recent version of `pandoc` in the Makefile, along with an `updatecli` manifest to keep it up to date.

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
The updatecli run shows the same result as the PR:

```diff
-PANDOC_VERSION ?= 2.10.1
+PANDOC_VERSION ?= 3.1.12.2
```

LGTM, thanks for this contribution!

🚀

**Comment by gounthar** [comment]
Thanks for accepting it. 🤗

**Review by dduportal — CHANGES_REQUESTED** [review]
The CI check fails with the following error:

```
Unknown option --atx-headers
```

Dismissing my review as it is a pandoc option but I haven't check: I don't know if it is related. Gotta check if I can reproduce locally with an `amd64` VM

**Comment by gounthar** [comment]
Ooopsie... I will also have a look at that.
Sorry. 🤷

**Comment by gounthar** [comment]
`make README` worked for me.

**Pull request merged**
