### PR TITLE
Update asciidoctor-diagram to 2.0.1 and minor changes

### PR DESCRIPTION
**Pull request by juracy**
- Editor config file
- New task: make latest
- Test for python3

### CODE REVIEW

**Comment by juracy** [comment]
I can split it in several PR's if necessary!

**Comment by dduportal** [comment]
Hello @juracy , thanks for this contribution ! 

It looks good, however could you split on different PR: it would help future changelog generation :)

**Comment by dduportal** [comment]
Hello @juracy , as #128 had been merged with the first release, is there still a reason to have the `latest` make goal?

**Comment by juracy** [comment]
@dduportal I'm not sure about latest task...but I'll split them!

**Pull request closed without merging**
