### PR TITLE
Update asciidoctor to 2.0.1

### PR DESCRIPTION
**Pull request by cexbrayat**
This is a WIP to open a discussion.

Some tests are currently failing with Asciidoctor v2.0.1

```bash
git:chore/bump-asciicdoctor-v2 ❯ bats ./tests/test_suite.bats
 ✓ We can build successfully the standard Docker image
 ✓ asciidoctor is installed and in version
 ✓ asciidoctor-pdf is installed and in version
 ✓ asciidoctor-revealjs is callable without error
 ✓ make is installed and in the path
 ✓ asciidoctor-epub3 is installed and in the path
 ✓ curl is installed and in the path
 ✓ bash is installed and in the path
 ✓ java is installed, in the path, and executable
 ✓ dot (from Graphviz) is installed and in the path
 ✓ asciidoctor-confluence is installed and in the path
 ✗ We can generate an HTML document from basic example
   (in test file tests/test_suite.bats, line 72)
     `docker run -t --rm \' failed
   asciidoctor: FAILED: 'asciidoctor-mathematical' could not be loaded
     Use --trace for backtrace
 ✗ We can generate a PDF document from basic example
   (in test file tests/test_suite.bats, line 81)
     `docker run -t --rm \' failed
   asciidoctor: FAILED: 'asciidoctor-mathematical' could not be loaded
     Use --trace for backtrace
 ✓ We can generate an HTML document with a diagram with asciidoctor-diagram as backend
 ✓ Bakoma Fonts are installed to render correctly the square root from asciidoctor-mathematical
 ✗ We can generate an HTML document with asciidoctor-mathematical as backend
   (in test file tests/test_suite.bats, line 119)
     `[ "${status}" -eq 0 ]' failed
 ✓ We can generate an HTML document with asciimath as backend
 ✗ We can generate a PDF document with asciidoctor-mathematical as backend
   (in test file tests/test_suite.bats, line 155)
     `[ "${status}" -eq 0 ]' failed

18 tests, 4 failures
```

@mojavelinux Is this expected? I also tried the image produced, and `asciidoctor-epub3` was failing.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks. We'll want to use 2.0.2 because there's a pretty nasty bug in 2.0.1.

**Comment by cexbrayat** [comment]
Sure, I'll update when it's available.

Should that fix the failing test?

**Comment by mojavelinux** [comment]
No idea.

2.0.2 will be out in a few hours.

**Comment by hakandilek** [comment]
> Should that fix the failing test?

@cexbrayat tests are failing due to the dependency `asciidoctor-mathematical-0.2.2` -> `asciidoctor-1.5.x`

asciidoctor/asciidoctor-mathematical#48 is supposed to fix that.

**Pull request closed without merging**
