### PR TITLE
GH-49: Implementation proposal for CI and CD

### PR DESCRIPTION
**Pull request by dduportal**
This Pull Request is a proposal implementation for #49 .

* It features the use of Travis-CI to build and test the docker-asciidoctor container
* GNU Make is used to provide a workflow
* Currently, the Deploy phase is proposed using my DockerHub account (https://hub.docker.com/r/dduportal/docker-asciidoctor/), to have a real life working example, with pushed images

*IMPORTANT* if this implementation of the deploy phase is fine, can someone with the right to the asciidoctor image on the DockerHub set up configuration or delegate to me the rights? The variable containing the token in https://travis-ci.org/asciidoctor/docker-asciidoctor/settings need to be adapted (as well as the curl destination in the deploy goal in this PR).

As side-kick setting, the `master` branch of this repository had been configured to be protected (need  CI check).

Ping @mojavelinux @mgreau , I would like your review and advise on this?

### CODE REVIEW

**Comment by dduportal** [comment]
Ping @mojavelinux @jirutka @mgreau for this (happy) new year 2018, I propose we enable fully the Travis CI on this repository to ensure feedback to contributors :)

**Comment by mgreau** [comment]
Thanks for working on it @dduportal
I'll test it and get back to you this weekend (on mobile now)

**Comment by mgreau** [comment]
> I'll test it and get back to you this weekend (on mobile now)

@dduportal sorry I finally can't review it this week, I'll let you know when I'm ready to do it.

**Comment by dduportal** [comment]
@mgreau no problem. I pinged you for the bugfix which was affecting users.
For this PR, time is needed to review it, so do not bother your self and do it when you'll have your mind free :)

Thanks for the feedback.

**Comment by dduportal** [comment]
Hello @mgreau @mojavelinux , I would like to bump on this PR (I know both of you are busy but just in case) :)

**Comment by dduportal** [comment]
My aplogies @gscheibel , I just realized I totally forgot to add you as approver / mention you here.

I owe you a beer/tea/coffee if you are at BreizhCamp or DevoxxFR.

**Comment by dduportal** [comment]
After discussing this with @mgreau at the DevoxxFR 2018, he agree on we merge this.

Let's rollback or change if you have any issue!

**Comment by mojavelinux** [comment]
Let's do it!

**Comment by mojavelinux** [comment]
Do you still need any access that you don't currently have?

**Comment by dduportal** [comment]
Hello @mojavelinux !

If you do not mind, I would need access to the DockerHub 's asciidoctor image, so I'll be able to:

* Fix https://github.com/asciidoctor/docker-asciidoctor/issues/42 
* Implement https://github.com/asciidoctor/docker-asciidoctor/issues/49 when we'll come on an agrement  (I also need to update it to reflect outcomes of the discussion I had with @mgreau  about "slim" image)

**Comment by dduportal** [comment]
And again @mojavelinux , thanks for you trust!

**Comment by mojavelinux** [comment]
Of course! You should be all set now.

**Comment by dduportal** [comment]
@mojavelinux sounds good, thanks a lot!

**Pull request merged**
