### PR TITLE
Update asciidoctor-pdf to 1.5.0.beta.3

### PR DESCRIPTION
**Pull request by juracy**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Please hold off until beta.2 is released. There are critical bugs in this release that we don't want to propagate.

**Comment by juracy** [comment]
> Please hold off until beta.2 is released. There are critical bugs in this release that we don't want to propagate.

Ok, I hadn't seen those bugs, I think https://github.com/asciidoctor/asciidoctor-pdf/issues/1144 is one them one!

**Comment by juracy** [comment]
By the way, I was thinking about how to automate this kind of update, when there aren't necessary manual updates. And with that kind of automation would be necessary multiple channels: stable, beta and so on (probably docker tags)

But, of course, it maybe over engineering....  ;)

**Comment by mojavelinux** [comment]
Once we get the libraries onto semantic versioning, I agree. For example, you could definitely do this with core today.

**Comment by dduportal** [comment]
Ping @mojavelinux , is the beta3 ok to be integrated here?

**Comment by mojavelinux** [comment]
Yes, please. Go for it. I'm eager to get feedback on this version.

Just to keep you in the loop, we may have one or two beta releases after that, then 1.5.0 is coming. We are very close. But I'm trying to get as many testers as possible and the Docker image will help with that.

**Pull request merged**
