### PR TITLE
WiP: parallel builds for erd

### PR DESCRIPTION
**Pull request by dduportal**
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>

### CODE REVIEW

**Comment by reitzig** [comment]
For a multi-stage build, you need to know very well what you need to copy on: in the most simple case it's a single binary, but there's no limit to the meh (I've build images with natively compiled Ruby gems, nightmare that ...). 

I don't know enough about the intent of #166 and erd to gauge where we land here. @sapientpants might know more about what the actually required stuff is.

**Comment by reitzig** [comment]
For a multi-stage build, you need to know very well what you need to copy on: in the most simple case it's a single binary, but there's no limit to the meh (I've build images with natively compiled Ruby gems, nightmare that ...). 

I don't know enough about the intent of #166 and erd to gauge where we land here. @sapientpants might know more about what the actually required stuff is.

**Comment by reitzig** [comment]
It _seems_ that cabal does indeed provice a single binary for erd here. At least, with

```Dockerfile
# This part unchanged
FROM alpine:3.13 AS erd
RUN apk add --no-cache --virtual .haskellmakedepends \
    alpine-sdk \
    cabal \
    ghc-dev \
    ghc \
    gmp-dev \
    gnupg \
    libffi-dev \
    linux-headers \
    perl-utils \
    wget \
    xz \
    zlib-dev \
  && cabal v2-update \
  && cabal v2-install erd

FROM alpine:3.13

RUN apk add --no-cache libffi gmp graphviz
COPY --from=erd root/.cabal/bin/erd /bin/
```

I get this:

```bash
$ docker run --rm -it adoc-test erd --version
erd-0.2.1.0 UNKNOWN
```

Haven't tested any actual functionality of erd, though.

FWIW, they document how to [build a statically-linked binary](https://github.com/BurntSushi/erd#building-statically-linked-executable); that's beyond my involvement with Haskell tooling, though. :'D

**Comment by dduportal** [comment]
As a starting point, the native APK package for `shellcheck` is a good example (as it is built with cabal as well): https://pkgs.alpinelinux.org/package/edge/community/x86_64/shellcheck

**Comment by reitzig** [comment]
@dduportal Do you have enough information to work on this?
I for one might be able to propose a new Dockerfile, but as I said, I won't be able to do any serious testing.

I'll note that multi-stage builds might also be able to reduce the size impact of building Ruby and Python dependencies, which currently happens with `RUN`s very similar to the new Haskell one.

**Comment by dduportal** [comment]
Hello @reitzig , even though I have all the informations, my bandwidth is full until mid-March so I won't be able to work on this topic until then.

Please feel free to open a PR if you feel ok to contribute, that would be a great help!
Regarding the tests, there is a test harness (look at https://github.com/asciidoctor/docker-asciidoctor#how-to-build-and-test) so you should feel safe to change things. Do not worry: I'll have time to review the PR, and if we break something, we'll be able to quickly fix it afterwards, don't be scared as we won't release until we both feel ok (the impact will be on the DockerIimage `latest` in the worst case scenario, which is not aimed to be stable).

Thanks a lot for your willingness, time and efforts!

**Comment by reitzig** [comment]
Cool! Here you go, that should get you started:  #184

**Comment by dduportal** [comment]
Closing in favor of #184

**Pull request closed without merging**
