### PR TITLE
Update asciidoctor-mathematical and adds font for math rendering

### PR DESCRIPTION
**Pull request by tarikgraba**
These commits should close issue #104 and issue #105

### CODE REVIEW

**Comment by dduportal** [comment]
Hello @tarikgraba , thanks a lot for this proposal!

There are two feedbacks for you:

- As the PR #101 had just been merged, could you rebase your PR to get the change in account please? Since #101 was about adding the font `ttf-dejavu` you might have a merge conflict top solve, sorry for that.
- Could you add a test case for asciidoctor-mathematical please? This test should fail with the version `0.3.0`, and work for `0.3.1` so we're sure this won't happen again in the future :)

**Comment by tarikgraba** [comment]
The commit should close issue #104

**Comment by tarikgraba** [comment]
For the test case I'll take a look.

**Comment by tarikgraba** [comment]
I have added a test in my last commit by modifying the latex math sample.
I can reproduce the bug by having inline math in list item.

**Comment by tarikgraba** [comment]
@dduportal Seems ok, no?

**Pull request merged**
