### PR TITLE
Add erd support

### PR DESCRIPTION
**Pull request by sapientpants**

### CODE REVIEW

**Review by dduportal — CHANGES_REQUESTED** [review]
Hi @sapientpants , thanks a lot for this contribution!

Could you update this PR to remove the commit related to #165 please? Thanks a lot

**Comment by sapientpants** [comment]
Cleaned up the PR as requested.

**Review by dduportal — APPROVED** [review]
LGTM 👍

**Comment by reitzig** [comment]
This added a whopping 1GB to the image size. Worth it? Discussion at #50.

**Comment by mojavelinux** [comment]
I agree that's rather excessive. That probably needs to be revisited.

**Pull request merged**
